### PR TITLE
#65: updated to latest JTS with package name change

### PR DESCRIPTION
**Pull request by smirnovegorv**
Updated JTS to latest 1.16.0 version with dependency name change (was com.vividsolutions.jts but from 1.15.0 it is org.locationtech.jts).

Updated version to 2.0 since this is a breaking change.

See https://github.com/locationtech/jts/blob/master/MIGRATION.md

### CODE REVIEW

**Review by filosganga — APPROVED** [review]
Thanks

**Comment by neseleznev** [comment]
Hi @filosganga. Thanks for this awesome library!
Do you plan to merge this PR and roll 2.0 out?

**Comment by filosganga** [comment]
Yes go ahead please

**Comment by filosganga** [comment]
@neseleznev It does not seem to build in CI

**Comment by jedi-philosopher** [comment]
CI reports looks a bit weird to me, there are no errors and no tests were run and it says like "The forked VM terminated without properly saying goodbye. VM crash or System.exit called?". Could you re-run the tests manually?

As for myself, I am using this version for quite a while already and everything seems fine. Tests also pass on my PC

**Comment by filosganga** [comment]
I see, let me try to kick off it again.

**Comment by filosganga** [comment]
The issue isn't in the PR itself, but I need to fix it to be able to release

**Comment by svbrunov** [comment]
Dear Filippo De Luca (@filosganga),

It seems that this version that contains these changes has not been released yet.  
Could you please release it?

It would be great to have this version published into the Maven Central Repository.

Best regards,  
Sergey Vyacheslavovich Brunov.

**Comment by filosganga** [comment]
Yes sure, will do this weekend thanks

**Comment by svbrunov** [comment]
Dear Filippo De Luca (@filosganga),

It sounds great!  
Thank you very much for the prompt response and support!

Best regards,  
Sergey Vyacheslavovich Brunov.

**Comment by svbrunov** [comment]
Dear Filippo De Luca (@filosganga),

Could you please share the status of the work on the release?  
May I help you somehow?

Best regards,  
Sergey Vyacheslavovich Brunov.

**Comment by svbrunov** [comment]
Dear Filippo De Luca (@filosganga),

Thank you for providing the 1.4.31 release!

Just for your information.
I have successfully upgraded the version of the `geogson` Maven dependencies from 1.4.2 to 1.4.31 for one of my projects.

Best regards,
Sergey Vyacheslavovich Brunov.

**Pull request merged**
